// Generated by scripts/generate-model.mjs from SAP's published service schemas.
// Do not edit; change model/fields.json and regenerate.
namespace aera.mirror.s4;

// API_PURCHASEORDER_PROCESS_SRV
entity A_PurchaseOrder {
  key PurchaseOrder : String(10);
  CompanyCode : String(4);
  PurchaseOrderType : String(4);
  PurchasingProcessingStatus : String(2);
  CreationDate : Date;
  LastChangeDateTime : Timestamp;
  Supplier : String(10);
  PurchasingOrganization : String(4);
  PurchasingGroup : String(3);
  PurchaseOrderDate : Date;
  DocumentCurrency : String(5);
  SupplyingPlant : String(4);
  to_PurchaseOrderItem : Composition of many A_PurchaseOrderItem on to_PurchaseOrderItem.PurchaseOrder = PurchaseOrder;
}

// API_PURCHASEORDER_PROCESS_SRV
entity A_PurchaseOrderItem {
  key PurchaseOrder : String(10);
  key PurchaseOrderItem : String(5);
  PurchasingDocumentDeletionCode : String(1);
  PurchaseOrderItemText : String(40);
  Plant : String(4);
  StorageLocation : String(4);
  OrderQuantity : Decimal(13, 3);
  PurchaseOrderQuantityUnit : String(3);
  DocumentCurrency : String(5);
  NetPriceAmount : Decimal(12, 3);
  NetPriceQuantity : Decimal(5, 0);
  IsCompletelyDelivered : Boolean;
  PurchaseOrderItemCategory : String(1);
  Material : String(40);
  to_ScheduleLine : Composition of many A_PurchaseOrderScheduleLine on to_ScheduleLine.PurchasingDocument = PurchaseOrder and to_ScheduleLine.PurchasingDocumentItem = PurchaseOrderItem;
}

// API_PURCHASEORDER_PROCESS_SRV
entity A_PurchaseOrderScheduleLine {
  key PurchasingDocument : String(10);
  key PurchasingDocumentItem : String(5);
  key ScheduleLine : String(4);
  DelivDateCategory : String(1);
  ScheduleLineDeliveryDate : Date;
  PurchaseOrderQuantityUnit : String(3);
  ScheduleLineOrderQuantity : Decimal(13, 3);
  ScheduleLineDeliveryTime : Time;
  ScheduleLineCommittedQuantity : Decimal(13, 3);
}

// API_MATERIAL_STOCK_SRV
entity A_MatlStkInAcctMod {
  key Material : String(40);
  key Plant : String(4);
  key StorageLocation : String(4);
  key Batch : String(10);
  key Supplier : String(10);
  key Customer : String(10);
  key WBSElementInternalID : String(24);
  key SDDocument : String(10);
  key SDDocumentItem : String(6);
  key InventorySpecialStockType : String(1);
  key InventoryStockType : String(2);
  MaterialBaseUnit : String(3);
  MatlWrhsStkQtyInMatlBaseUnit : Decimal(31, 14);
}

// API_SALES_ORDER_SRV
entity A_SalesOrder {
  key SalesOrder : String(10);
  SalesOrderType : String(4);
  SoldToParty : String(10);
  CreationDate : Date;
  SalesOrderDate : Date;
  TotalNetAmount : Decimal(16, 3);
  TransactionCurrency : String(5);
  RequestedDeliveryDate : Date;
  CustomerGroup : String(2);
  to_Item : Composition of many A_SalesOrderItem on to_Item.SalesOrder = SalesOrder;
}

// API_SALES_ORDER_SRV
entity A_SalesOrderItem {
  key SalesOrder : String(10);
  key SalesOrderItem : String(6);
  SalesOrderItemText : String(40);
  Material : String(40);
  RequestedQuantity : Decimal(15, 3);
  RequestedQuantityUnit : String(3);
  TransactionCurrency : String(5);
  NetAmount : Decimal(16, 3);
  ProductionPlant : String(4);
  to_ScheduleLine : Composition of many A_SalesOrderScheduleLine on to_ScheduleLine.SalesOrder = SalesOrder and to_ScheduleLine.SalesOrderItem = SalesOrderItem;
}

// API_SALES_ORDER_SRV
entity A_SalesOrderScheduleLine {
  key SalesOrder : String(10);
  key SalesOrderItem : String(6);
  key ScheduleLine : String(4);
  RequestedDeliveryDate : Date;
  ConfirmedDeliveryDate : Date;
  OrderQuantityUnit : String(3);
  ScheduleLineOrderQuantity : Decimal(13, 3);
}

// API_PRODUCTION_ORDER_2_SRV
entity A_ProductionOrder_2 {
  key ManufacturingOrder : String(12);
  ManufacturingOrderType : String(4);
  Material : String(40);
  ProductionPlant : String(4);
  MRPController : String(3);
  SalesOrder : String(10);
  SalesOrderItem : String(6);
  MfgOrderPlannedStartDate : Date;
  MfgOrderPlannedStartTime : Time;
  MfgOrderPlannedEndDate : Date;
  MfgOrderPlannedEndTime : Time;
  ProductionUnit : String(3);
  TotalQuantity : Decimal(13, 3);
  OrderIsReleased : String(1);
  to_ProductionOrderComponent : Composition of many A_ProductionOrderComponent_2 on to_ProductionOrderComponent.ManufacturingOrder = ManufacturingOrder;
}

// API_PRODUCTION_ORDER_2_SRV
entity A_ProductionOrderComponent_2 {
  key Reservation : String(10);
  key ReservationItem : String(4);
  Material : String(40);
  Plant : String(4);
  ManufacturingOrder : String(12);
  MatlCompRequirementDate : Date;
  MatlCompRequirementTime : Time;
  BaseUnit : String(3);
  RequiredQuantity : Decimal(13, 3);
  WithdrawnQuantity : Decimal(13, 3);
}

// API_BUSINESS_PARTNER
entity A_BusinessPartner {
  key BusinessPartner : String(10);
  Supplier : String(10);
  CorrespondenceLanguage : String(2);
  BusinessPartnerCategory : String(1);
  BusinessPartnerGrouping : String(4);
  BusinessPartnerFullName : String(81);
  BusinessPartnerName : String(81);
}

// API_BUSINESS_PARTNER
entity A_Supplier {
  key Supplier : String(10);
  SupplierName : String(80);
  SupplierFullName : String(220);
  PurchasingIsBlocked : Boolean;
}

// API_BUSINESS_PARTNER
entity A_BusinessPartnerAddress {
  key BusinessPartner : String(10);
  key AddressID : String(10);
  CityName : String(40);
  Country : String(3);
}

// API_BUSINESS_PARTNER
entity A_AddressEmailAddress {
  key AddressID : String(10);
  key Person : String(10);
  key OrdinalNumber : String(3);
  IsDefaultEmailAddress : Boolean;
  EmailAddress : String(241);
}

// API_BUSINESS_PARTNER
entity A_AddressPhoneNumber {
  key AddressID : String(10);
  key Person : String(10);
  key OrdinalNumber : String(3);
  DestinationLocationCountry : String(3);
  IsDefaultPhoneNumber : Boolean;
  PhoneNumber : String(30);
  InternationalPhoneNumber : String(30);
  PhoneNumberType : String(1);
}

// API_MATERIAL_DOCUMENT_SRV
entity A_MaterialDocumentItem {
  key MaterialDocumentYear : String(4);
  key MaterialDocument : String(10);
  key MaterialDocumentItem : String(4);
  Material : String(40);
  Plant : String(4);
  StorageLocation : String(4);
  GoodsMovementType : String(3);
  PurchaseOrder : String(10);
  PurchaseOrderItem : String(5);
  MaterialBaseUnit : String(3);
  QuantityInBaseUnit : Decimal(13, 3);
  EntryUnit : String(3);
  QuantityInEntryUnit : Decimal(13, 3);
}
