// Generate db/s4.cds from SAP's published service schemas (SRD 6.6.2, IR-02).
//
// Field names and types are copied mechanically from the CSN that SAP ships in its
// @sap/cloud-sdk-vdm-* packages (generated from the official EDMX), fetched by
// scripts/fetch-sap-schemas.mjs. model/fields.json
// only selects which of them the Mirror exposes; any name SAP does not define fails
// generation. `--check` compares the committed file instead of writing it.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { cacheFile } from "./fetch-sap-schemas.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(root, "db", "s4.cds");

export function loadServiceSchema(packageName) {
  const file = cacheFile(packageName);
  if (!existsSync(file)) {
    throw new Error(`${packageName} schema missing; run node scripts/fetch-sap-schemas.mjs`);
  }
  return JSON.parse(readFileSync(file, "utf8"));
}

function cdsType(element, where) {
  const type = element.type?.replace(/^cds\./, "");
  switch (type) {
    case "String":
      return element.length ? `String(${element.length})` : "String";
    case "Decimal":
      return `Decimal(${element.precision}, ${element.scale})`;
    case "Boolean":
    case "Date":
    case "Time":
    case "Timestamp":
    case "DateTime":
    case "UUID":
    case "Integer":
    case "Int64":
    case "Double":
      return type;
    default:
      throw new Error(`${where}: unsupported type ${element.type}`);
  }
}

export function generate(selection, loadSchema = loadServiceSchema) {
  const lines = [
    "// Generated by scripts/generate-model.mjs from SAP's published service schemas.",
    "// Do not edit; change model/fields.json and regenerate.",
    "namespace aera.mirror.s4;",
    "",
  ];
  for (const [service, spec] of Object.entries(selection.services)) {
    const definitions = loadSchema(spec.package).definitions;
    const entity = (name) => {
      const definition = definitions[`${service}.${name}`];
      if (!definition || definition.kind !== "entity") {
        throw new Error(`${service} defines no entity ${name}`);
      }
      return definition;
    };
    for (const [name, wanted] of Object.entries(spec.entities)) {
      const elements = entity(name).elements;
      const keys = Object.keys(elements).filter((field) => elements[field].key);
      const unknown = wanted.filter((field) => !(field in elements));
      if (unknown.length) throw new Error(`${service}.${name} has no field(s) ${unknown}`);
      lines.push(`// ${service}`, `entity ${name} {`);
      for (const field of [...keys, ...wanted.filter((field) => !keys.includes(field))]) {
        const element = elements[field];
        lines.push(`  ${element.key ? "key " : ""}${field} : ${cdsType(element, `${name}.${field}`)};`);
      }
      for (const composition of spec.compositions.filter((c) => c.parent === name)) {
        if (!(composition.name in elements)) {
          throw new Error(`${service}.${name} has no navigation ${composition.name}`);
        }
        const child = entity(composition.child).elements;
        const condition = Object.entries(composition.on).map(([childField, parentField]) => {
          if (!(childField in child) || !(parentField in elements)) {
            throw new Error(`${service}.${name}.${composition.name}: bad join ${childField}`);
          }
          return `${composition.name}.${childField} = ${parentField}`;
        });
        lines.push(
          `  ${composition.name} : Composition of many ${composition.child} on ${condition.join(" and ")};`,
        );
      }
      lines.push("}", "");
    }
  }
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const selection = JSON.parse(readFileSync(join(root, "model", "fields.json"), "utf8"));
  const text = generate(selection);
  if (process.argv.includes("--check")) {
    if (readFileSync(OUTPUT, "utf8") !== text) {
      console.error("db/s4.cds is out of date; run scripts/generate-model.mjs");
      process.exit(1);
    }
    console.log("db/s4.cds matches SAP's schemas and model/fields.json");
  } else {
    writeFileSync(OUTPUT, text);
    console.log(`wrote ${OUTPUT}`);
  }
}
